# Generated by Django 3.1.2 on 2020-10-15 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
