# Generated by Django 3.1.2 on 2020-10-16 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userprofile_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locationText', models.CharField(max_length=20)),
                ('locationUrl', models.URLField(max_length=500)),
                ('typeA', models.IntegerField()),
                ('typeB', models.IntegerField()),
                ('typeC', models.IntegerField()),
                ('wheelchair', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProcessorPoint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='users.chargespot')),
            ],
        ),
    ]
