# Generated by Django 3.1.2 on 2020-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201016_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargespot',
            name='locationUrl',
            field=models.URLField(max_length=100000),
        ),
    ]
