# Generated by Django 3.1.2 on 2020-10-16 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201016_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargespot',
            name='name',
            field=models.CharField(default='chargeSpot1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processorpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
