# Generated by Django 3.1.2 on 2020-10-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201016_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorpoint',
            name='belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='users.chargespot'),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batteryVolt', models.IntegerField()),
                ('fullVolt', models.IntegerField()),
                ('panels', models.IntegerField()),
                ('panelsVolt', models.IntegerField()),
                ('belongs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.chargespot')),
            ],
        ),
    ]
