# Generated by Django 3.1.2 on 2020-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201016_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='batteryVolt',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='management',
            name='fullVolt',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='management',
            name='panelsVolt',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
