# Generated by Django 3.1.2 on 2020-10-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_chargehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargehistory',
            old_name='user',
            new_name='userHistory',
        ),
    ]
