# Generated by Django 3.1.2 on 2020-10-22 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20201022_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargehistory',
            options={'ordering': ['duration']},
        ),
        migrations.AlterUniqueTogether(
            name='chargehistory',
            unique_together={('userHistory', 'date', 'duration')},
        ),
    ]
