# Generated by Django 3.1.2 on 2020-10-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201022_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargehistory',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='chargehistory',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.chargespot'),
        ),
    ]
